
const boardConfig = [
  { id: 1, name: 'Go', type: 'go' },
  { id: 2, name: 'Mumbai', type: 'property' },
  { id: 3, name: 'Water Works', type: 'utility' },
  { id: 4, name: 'Railways', type: 'railroad' },
  { id: 5, name: 'Ahmedabad', type: 'property' },
  { id: 6, name: 'Income Tax', type: 'tax' },
  { id: 7, name: 'Indore', type: 'property' },
  { id: 8, name: 'Chance', type: 'chance' },
  { id: 9, name: 'Jaipur', type: 'property' },
  { id: 10, name: 'Jail', type: 'jail' },
  { id: 11, name: 'New Delhi', type: 'property' },
  { id: 12, name: 'Chandigarh', type: 'property' },
  { id: 13, name: 'Electric Company', type: 'utility' },
  { id: 14, name: 'BEST', type: 'railroad' },
  { id: 15, name: 'Shimla', type: 'property' },
  { id: 16, name: 'Amritsar', type: 'property' },
  { id: 17, name: 'Community Chest', type: 'community' },
  { id: 18, name: 'Srinagar', type: 'property' },
  { id: 19, name: 'Club', type: 'parking' },
  { id: 20, name: 'Agra', type: 'property' },
  { id: 21, name: 'Chance', type: 'chance' },
  { id: 22, name: 'Kanpur', type: 'property' },
  { id: 23, name: 'Patna', type: 'property' },
  { id: 24, name: 'Darjeeling', type: 'property' },
  { id: 25, name: 'Air India', type: 'railroad' },
  { id: 26, name: 'Kolkata', type: 'property' },
  { id: 27, name: 'Hyderabad', type: 'property' },
  { id: 28, name: 'Rest House', type: 'go_to_jail' },
  { id: 29, name: 'Chennai', type: 'property' },
  { id: 30, name: 'Community Chest', type: 'community' },
  { id: 31, name: 'Bengaluru', type: 'property' },
  { id: 32, name: 'Wealth Tax', type: 'tax' },
  { id: 33, name: 'Mysore', type: 'property' },
  { id: 34, name: 'Cochin', type: 'property' },
  { id: 35, name: 'Motor Boat', type: 'utility' },
  { id: 36, name: 'Goa', type: 'property' }
];
  module.exports = { boardConfig };
  